<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <Version>7.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zps.Core\Zps.Core.csproj" />
    <ProjectReference Include="..\Zps.Data\Zps.Data.csproj" />
    <ProjectReference Include="..\Zps.Hardware\Zps.Hardware.csproj" />
    <ProjectReference Include="..\Zps.Updater\Zps.Updater.csproj" />
  </ItemGroup>

</Project>
